[package]
name = "sn_node_rpc_types"
version = "0.1.0"
authors = ["Alan Armero <scorchdev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
